/** UK places people search for Christian dating. Names are the place, not a claim about members. */

export const REGIONS = [
  { slug: "greater-london", name: "Greater London" },
  { slug: "south-east-england", name: "South East England" },
  { slug: "south-west-england", name: "South West England" },
  { slug: "east-of-england", name: "East of England" },
  { slug: "east-midlands", name: "East Midlands" },
  { slug: "west-midlands", name: "West Midlands" },
  { slug: "yorkshire-and-the-humber", name: "Yorkshire and the Humber" },
  { slug: "north-west-england", name: "North West England" },
  { slug: "north-east-england", name: "North East England" },
  { slug: "scotland", name: "Scotland" },
  { slug: "wales", name: "Wales" },
  { slug: "northern-ireland", name: "Northern Ireland" },
] as const;

export type RegionSlug = (typeof REGIONS)[number]["slug"];

export type PlaceKind = "city" | "town";

export type Place = {
  slug: string;
  name: string;
  kind: PlaceKind;
  region: RegionSlug;
};

type Row = [slug: string, name: string, kind: PlaceKind];

const ROWS: Record<RegionSlug, Row[]> = {
  "greater-london": [
    ["london", "London", "city"],
    ["croydon", "Croydon", "town"],
    ["kingston-upon-thames", "Kingston upon Thames", "town"],
    ["bromley", "Bromley", "town"],
    ["richmond", "Richmond", "town"],
    ["enfield", "Enfield", "town"],
    ["ealing", "Ealing", "town"],
    ["barnet", "Barnet", "town"],
    ["harrow", "Harrow", "town"],
    ["westminster", "Westminster", "town"],
    ["islington", "Islington", "town"],
    ["camden", "Camden", "town"],
    ["hackney", "Hackney", "town"],
    ["greenwich", "Greenwich", "town"],
    ["lewisham", "Lewisham", "town"],
    ["southwark", "Southwark", "town"],
    ["lambeth", "Lambeth", "town"],
    ["wandsworth", "Wandsworth", "town"],
    ["hammersmith", "Hammersmith", "town"],
    ["kensington", "Kensington", "town"],
    ["chelsea", "Chelsea", "town"],
    ["wimbledon", "Wimbledon", "town"],
    ["ilford", "Ilford", "town"],
    ["romford", "Romford", "town"],
    ["uxbridge", "Uxbridge", "town"],
    ["stratford", "Stratford", "town"],
    ["clapham", "Clapham", "town"],
    ["wembley", "Wembley", "town"],
    ["woolwich", "Woolwich", "town"],
    ["orpington", "Orpington", "town"],
    ["twickenham", "Twickenham", "town"],
    ["putney", "Putney", "town"],
    ["chiswick", "Chiswick", "town"],
    ["finchley", "Finchley", "town"],
    ["walthamstow", "Walthamstow", "town"],
    ["beckenham", "Beckenham", "town"],
    ["brixton", "Brixton", "town"],
    ["fulham", "Fulham", "town"],
    ["hampstead", "Hampstead", "town"],
    ["tottenham", "Tottenham", "town"],
    ["barking", "Barking", "town"],
    ["hounslow", "Hounslow", "town"],
    ["bexleyheath", "Bexleyheath", "town"],
    ["sidcup", "Sidcup", "town"],
    ["streatham", "Streatham", "town"],
    ["tooting", "Tooting", "town"],
    ["battersea", "Battersea", "town"],
    ["shoreditch", "Shoreditch", "town"],
    ["wood-green", "Wood Green", "town"],
    ["southall", "Southall", "town"],
    ["hayes", "Hayes", "town"],
    ["feltham", "Feltham", "town"],
    ["surbiton", "Surbiton", "town"],
    ["peckham", "Peckham", "town"],
    ["dulwich", "Dulwich", "town"],
    ["acton", "Acton", "town"],
    ["muswell-hill", "Muswell Hill", "town"],
    ["notting-hill", "Notting Hill", "town"],
    ["canary-wharf", "Canary Wharf", "town"],
    ["dagenham", "Dagenham", "town"],
    ["chingford", "Chingford", "town"],
    ["pinner", "Pinner", "town"],
    ["edgware", "Edgware", "town"],
    ["catford", "Catford", "town"],
    ["eltham", "Eltham", "town"],
    ["hornchurch", "Hornchurch", "town"],
    ["ruislip", "Ruislip", "town"],
    ["kilburn", "Kilburn", "town"],
    ["bethnal-green", "Bethnal Green", "town"],
  ],
  "south-east-england": [
    ["brighton", "Brighton", "city"],
    ["reading", "Reading", "city"],
    ["milton-keynes", "Milton Keynes", "city"],
    ["oxford", "Oxford", "city"],
    ["southampton", "Southampton", "city"],
    ["portsmouth", "Portsmouth", "city"],
    ["guildford", "Guildford", "town"],
    ["canterbury", "Canterbury", "city"],
    ["maidstone", "Maidstone", "town"],
    ["slough", "Slough", "town"],
    ["tunbridge-wells", "Tunbridge Wells", "town"],
    ["winchester", "Winchester", "city"],
    ["basingstoke", "Basingstoke", "town"],
    ["high-wycombe", "High Wycombe", "town"],
    ["crawley", "Crawley", "town"],
    ["horsham", "Horsham", "town"],
    ["chichester", "Chichester", "city"],
    ["eastbourne", "Eastbourne", "town"],
    ["hastings", "Hastings", "town"],
    ["worthing", "Worthing", "town"],
    ["windsor", "Windsor", "town"],
    ["woking", "Woking", "town"],
    ["folkestone", "Folkestone", "town"],
    ["dover", "Dover", "town"],
    ["ashford", "Ashford", "town"],
    ["sevenoaks", "Sevenoaks", "town"],
    ["dartford", "Dartford", "town"],
    ["gravesend", "Gravesend", "town"],
    ["chatham", "Chatham", "town"],
    ["rochester", "Rochester", "town"],
    ["farnborough", "Farnborough", "town"],
    ["aldershot", "Aldershot", "town"],
    ["epsom", "Epsom", "town"],
    ["reigate", "Reigate", "town"],
    ["maidenhead", "Maidenhead", "town"],
    ["bracknell", "Bracknell", "town"],
    ["aylesbury", "Aylesbury", "town"],
    ["banbury", "Banbury", "town"],
    ["sittingbourne", "Sittingbourne", "town"],
    ["gillingham", "Gillingham", "town"],
    ["margate", "Margate", "town"],
    ["ramsgate", "Ramsgate", "town"],
    ["tonbridge", "Tonbridge", "town"],
    ["fareham", "Fareham", "town"],
    ["andover", "Andover", "town"],
    ["farnham", "Farnham", "town"],
    ["newbury", "Newbury", "town"],
    ["whitstable", "Whitstable", "town"],
    ["bicester", "Bicester", "town"],
  ],
  "south-west-england": [
    ["bristol", "Bristol", "city"],
    ["bath", "Bath", "city"],
    ["bournemouth", "Bournemouth", "city"],
    ["plymouth", "Plymouth", "city"],
    ["exeter", "Exeter", "city"],
    ["gloucester", "Gloucester", "city"],
    ["swindon", "Swindon", "town"],
    ["cheltenham", "Cheltenham", "town"],
    ["taunton", "Taunton", "town"],
    ["truro", "Truro", "city"],
    ["salisbury", "Salisbury", "city"],
    ["torquay", "Torquay", "town"],
    ["poole", "Poole", "town"],
    ["yeovil", "Yeovil", "town"],
    ["weston-super-mare", "Weston-super-Mare", "town"],
    ["weymouth", "Weymouth", "town"],
    ["barnstaple", "Barnstaple", "town"],
    ["penzance", "Penzance", "town"],
    ["newton-abbot", "Newton Abbot", "town"],
    ["paignton", "Paignton", "town"],
    ["exmouth", "Exmouth", "town"],
    ["bridgwater", "Bridgwater", "town"],
    ["chippenham", "Chippenham", "town"],
    ["stroud", "Stroud", "town"],
    ["newquay", "Newquay", "town"],
    ["falmouth", "Falmouth", "town"],
    ["st-austell", "St Austell", "town"],
    ["frome", "Frome", "town"],
  ],
  "east-of-england": [
    ["cambridge", "Cambridge", "city"],
    ["norwich", "Norwich", "city"],
    ["ipswich", "Ipswich", "town"],
    ["peterborough", "Peterborough", "city"],
    ["luton", "Luton", "town"],
    ["southend", "Southend", "town"],
    ["colchester", "Colchester", "city"],
    ["chelmsford", "Chelmsford", "city"],
    ["bedford", "Bedford", "town"],
    ["stevenage", "Stevenage", "town"],
    ["watford", "Watford", "town"],
    ["st-albans", "St Albans", "city"],
    ["basildon", "Basildon", "town"],
    ["kings-lynn", "King's Lynn", "town"],
    ["bury-st-edmunds", "Bury St Edmunds", "town"],
    ["hemel-hempstead", "Hemel Hempstead", "town"],
    ["harlow", "Harlow", "town"],
    ["bishops-stortford", "Bishop's Stortford", "town"],
    ["welwyn-garden-city", "Welwyn Garden City", "town"],
    ["brentwood", "Brentwood", "town"],
    ["great-yarmouth", "Great Yarmouth", "town"],
    ["lowestoft", "Lowestoft", "town"],
    ["huntingdon", "Huntingdon", "town"],
    ["st-neots", "St Neots", "town"],
    ["ely", "Ely", "city"],
    ["braintree", "Braintree", "town"],
    ["hitchin", "Hitchin", "town"],
    ["grays", "Grays", "town"],
    ["clacton-on-sea", "Clacton-on-Sea", "town"],
    ["billericay", "Billericay", "town"],
  ],
  "east-midlands": [
    ["nottingham", "Nottingham", "city"],
    ["leicester", "Leicester", "city"],
    ["derby", "Derby", "city"],
    ["northampton", "Northampton", "town"],
    ["lincoln", "Lincoln", "city"],
    ["mansfield", "Mansfield", "town"],
    ["loughborough", "Loughborough", "town"],
    ["chesterfield", "Chesterfield", "town"],
    ["kettering", "Kettering", "town"],
    ["corby", "Corby", "town"],
    ["grantham", "Grantham", "town"],
    ["hinckley", "Hinckley", "town"],
    ["newark", "Newark", "town"],
    ["worksop", "Worksop", "town"],
    ["boston", "Boston", "town"],
    ["market-harborough", "Market Harborough", "town"],
    ["wellingborough", "Wellingborough", "town"],
    ["ilkeston", "Ilkeston", "town"],
    ["melton-mowbray", "Melton Mowbray", "town"],
    ["coalville", "Coalville", "town"],
    ["spalding", "Spalding", "town"],
  ],
  "west-midlands": [
    ["birmingham", "Birmingham", "city"],
    ["coventry", "Coventry", "city"],
    ["wolverhampton", "Wolverhampton", "city"],
    ["stoke-on-trent", "Stoke-on-Trent", "city"],
    ["worcester", "Worcester", "city"],
    ["solihull", "Solihull", "town"],
    ["dudley", "Dudley", "town"],
    ["walsall", "Walsall", "town"],
    ["rugby", "Rugby", "town"],
    ["shrewsbury", "Shrewsbury", "town"],
    ["hereford", "Hereford", "city"],
    ["stafford", "Stafford", "town"],
    ["tamworth", "Tamworth", "town"],
    ["sutton-coldfield", "Sutton Coldfield", "town"],
    ["west-bromwich", "West Bromwich", "town"],
    ["nuneaton", "Nuneaton", "town"],
    ["redditch", "Redditch", "town"],
    ["telford", "Telford", "town"],
    ["lichfield", "Lichfield", "city"],
    ["cannock", "Cannock", "town"],
    ["kidderminster", "Kidderminster", "town"],
    ["leamington-spa", "Leamington Spa", "town"],
    ["stratford-upon-avon", "Stratford-upon-Avon", "town"],
    ["newcastle-under-lyme", "Newcastle-under-Lyme", "town"],
    ["burton-upon-trent", "Burton upon Trent", "town"],
  ],
  "yorkshire-and-the-humber": [
    ["leeds", "Leeds", "city"],
    ["sheffield", "Sheffield", "city"],
    ["bradford", "Bradford", "city"],
    ["york", "York", "city"],
    ["hull", "Hull", "city"],
    ["doncaster", "Doncaster", "city"],
    ["huddersfield", "Huddersfield", "town"],
    ["wakefield", "Wakefield", "city"],
    ["harrogate", "Harrogate", "town"],
    ["barnsley", "Barnsley", "town"],
    ["rotherham", "Rotherham", "town"],
    ["scarborough", "Scarborough", "town"],
    ["grimsby", "Grimsby", "town"],
    ["halifax", "Halifax", "town"],
    ["dewsbury", "Dewsbury", "town"],
    ["keighley", "Keighley", "town"],
    ["scunthorpe", "Scunthorpe", "town"],
    ["bridlington", "Bridlington", "town"],
    ["beverley", "Beverley", "town"],
    ["castleford", "Castleford", "town"],
    ["skipton", "Skipton", "town"],
    ["selby", "Selby", "town"],
  ],
  "north-west-england": [
    ["manchester", "Manchester", "city"],
    ["liverpool", "Liverpool", "city"],
    ["preston", "Preston", "city"],
    ["blackpool", "Blackpool", "town"],
    ["chester", "Chester", "city"],
    ["warrington", "Warrington", "town"],
    ["bolton", "Bolton", "town"],
    ["stockport", "Stockport", "town"],
    ["oldham", "Oldham", "town"],
    ["wigan", "Wigan", "town"],
    ["blackburn", "Blackburn", "town"],
    ["lancaster", "Lancaster", "city"],
    ["carlisle", "Carlisle", "city"],
    ["southport", "Southport", "town"],
    ["salford", "Salford", "city"],
    ["rochdale", "Rochdale", "town"],
    ["bury", "Bury", "town"],
    ["burnley", "Burnley", "town"],
    ["crewe", "Crewe", "town"],
    ["macclesfield", "Macclesfield", "town"],
    ["birkenhead", "Birkenhead", "town"],
    ["st-helens", "St Helens", "town"],
    ["altrincham", "Altrincham", "town"],
    ["chorley", "Chorley", "town"],
    ["barrow-in-furness", "Barrow-in-Furness", "town"],
    ["kendal", "Kendal", "town"],
    ["morecambe", "Morecambe", "town"],
  ],
  "north-east-england": [
    ["newcastle", "Newcastle", "city"],
    ["sunderland", "Sunderland", "city"],
    ["middlesbrough", "Middlesbrough", "town"],
    ["durham", "Durham", "city"],
    ["gateshead", "Gateshead", "town"],
    ["darlington", "Darlington", "town"],
    ["hartlepool", "Hartlepool", "town"],
    ["stockton-on-tees", "Stockton-on-Tees", "town"],
    ["morpeth", "Morpeth", "town"],
    ["south-shields", "South Shields", "town"],
    ["whitley-bay", "Whitley Bay", "town"],
    ["blyth", "Blyth", "town"],
    ["hexham", "Hexham", "town"],
    ["bishop-auckland", "Bishop Auckland", "town"],
    ["redcar", "Redcar", "town"],
    ["peterlee", "Peterlee", "town"],
    ["ashington", "Ashington", "town"],
  ],
  scotland: [
    ["glasgow", "Glasgow", "city"],
    ["edinburgh", "Edinburgh", "city"],
    ["aberdeen", "Aberdeen", "city"],
    ["dundee", "Dundee", "city"],
    ["inverness", "Inverness", "city"],
    ["stirling", "Stirling", "city"],
    ["perth", "Perth", "city"],
    ["paisley", "Paisley", "town"],
    ["dunfermline", "Dunfermline", "town"],
    ["falkirk", "Falkirk", "town"],
    ["ayr", "Ayr", "town"],
    ["dumfries", "Dumfries", "town"],
    ["east-kilbride", "East Kilbride", "town"],
    ["livingston", "Livingston", "town"],
    ["kilmarnock", "Kilmarnock", "town"],
    ["kirkcaldy", "Kirkcaldy", "town"],
    ["hamilton", "Hamilton", "town"],
    ["motherwell", "Motherwell", "town"],
    ["greenock", "Greenock", "town"],
    ["irvine", "Irvine", "town"],
    ["glenrothes", "Glenrothes", "town"],
    ["elgin", "Elgin", "town"],
  ],
  wales: [
    ["cardiff", "Cardiff", "city"],
    ["swansea", "Swansea", "city"],
    ["newport", "Newport", "city"],
    ["wrexham", "Wrexham", "city"],
    ["bridgend", "Bridgend", "town"],
    ["neath", "Neath", "town"],
    ["llanelli", "Llanelli", "town"],
    ["carmarthen", "Carmarthen", "town"],
    ["bangor", "Bangor", "city"],
    ["aberystwyth", "Aberystwyth", "town"],
    ["caernarfon", "Caernarfon", "town"],
    ["barry", "Barry", "town"],
    ["merthyr-tydfil", "Merthyr Tydfil", "town"],
    ["caerphilly", "Caerphilly", "town"],
    ["cwmbran", "Cwmbran", "town"],
    ["llandudno", "Llandudno", "town"],
    ["rhyl", "Rhyl", "town"],
    ["colwyn-bay", "Colwyn Bay", "town"],
    ["pontypridd", "Pontypridd", "town"],
    ["port-talbot", "Port Talbot", "town"],
  ],
  "northern-ireland": [
    ["belfast", "Belfast", "city"],
    ["derry", "Derry", "city"],
    ["lisburn", "Lisburn", "city"],
    ["newry", "Newry", "city"],
    ["bangor-county-down", "Bangor, County Down", "town"],
    ["ballymena", "Ballymena", "town"],
    ["coleraine", "Coleraine", "town"],
    ["omagh", "Omagh", "town"],
    ["enniskillen", "Enniskillen", "town"],
    ["armagh", "Armagh", "city"],
    ["antrim", "Antrim", "town"],
    ["newtownabbey", "Newtownabbey", "town"],
    ["craigavon", "Craigavon", "town"],
    ["carrickfergus", "Carrickfergus", "town"],
    ["newtownards", "Newtownards", "town"],
    ["portadown", "Portadown", "town"],
    ["larne", "Larne", "town"],
    ["downpatrick", "Downpatrick", "town"],
    ["dungannon", "Dungannon", "town"],
  ],
};

export const PLACES: Place[] = REGIONS.flatMap((region) =>
  ROWS[region.slug].map(([slug, name, kind]) => ({ slug, name, kind, region: region.slug })),
);

const bySlug = new Map(PLACES.map((place) => [place.slug, place]));

export function regionBySlug(slug: string) {
  return REGIONS.find((region) => region.slug === slug);
}

export function placeBySlug(slug: string): Place | undefined {
  return bySlug.get(slug);
}

export function placesInRegion(slug: string): Place[] {
  return PLACES.filter((place) => place.region === slug);
}

/** The main city of a region, when this place is not that city. Not a distance claim. */
export function regionPrimary(place: Place): Place | undefined {
  const primary = placesInRegion(place.region).find((item) => item.kind === "city");
  if (!primary || primary.slug === place.slug) return undefined;
  return primary;
}

/** Other places in the same region. Not a claim that they are the nearest by road. */
export function alsoInRegion(place: Place, count = 3): Place[] {
  const group = placesInRegion(place.region);
  const index = group.findIndex((item) => item.slug === place.slug);
  const picks: Place[] = [];
  for (let step = 1; picks.length < count && step < group.length; step += 1) {
    const next = group[(index + step) % group.length];
    if (next && next.slug !== place.slug) picks.push(next);
  }
  return picks;
}

/** Largest places, where age, Catholic, divorce, and free combinations are real searches. */
export const TOP_PLACE_SLUGS = [
  "london",
  "birmingham",
  "manchester",
  "leeds",
  "glasgow",
  "liverpool",
  "newcastle",
  "sheffield",
  "bristol",
  "edinburgh",
  "cardiff",
  "belfast",
  "leicester",
  "nottingham",
  "coventry",
  "brighton",
  "southampton",
  "oxford",
  "cambridge",
  "york",
  "bath",
  "bournemouth",
  "norwich",
  "sunderland",
  "reading",
  "plymouth",
  "wolverhampton",
  "derby",
  "aberdeen",
  "swansea",
  "hull",
  "bradford",
  "milton-keynes",
  "peterborough",
  "stoke-on-trent",
] as const;

/** Cities where age, Anglican, and widowed searches are worth their own URLs. */
export const HUB_PLACE_SLUGS = [
  "london",
  "birmingham",
  "manchester",
  "leeds",
  "glasgow",
  "liverpool",
  "newcastle",
  "sheffield",
  "bristol",
  "edinburgh",
  "cardiff",
  "belfast",
  "nottingham",
  "leicester",
] as const;

export function isTopPlace(slug: string): boolean {
  return (TOP_PLACE_SLUGS as readonly string[]).includes(slug);
}

export function isHubPlace(slug: string): boolean {
  return (HUB_PLACE_SLUGS as readonly string[]).includes(slug);
}

export function placePath(place: Place): string {
  return `/christian-dating/in/${place.slug}`;
}

export function regionPath(slug: RegionSlug): string {
  return `/christian-dating/${slug}`;
}
