export const PROVIDER_CAPABILITY_MATRIX = [
  {
    feature: "Transactional email",
    interfaceName: "sendTransactionalEmail",
    developmentAdapter: "email.dev / email.resend when key present",
    productionProvider: "Resend",
    dataStoredLocally: "notifications, provider_results, audit_events",
    failureBehaviour: "Job retries then dead-letters; UI must not claim delivery",
    verificationState: "Implemented; production send blocked until RESEND_API_KEY verified",
  },
  {
    feature: "SMS / mobile verification",
    interfaceName: "sendSmsCode / verifySmsCode",
    developmentAdapter: "sms.dev",
    productionProvider: "Open — Twilio or equivalent",
    dataStoredLocally: "verification_checks, provider_results",
    failureBehaviour: "pass/fail/pending/unavailable states recorded; no public badge on fail",
    verificationState: "Sandbox only",
  },
  {
    feature: "Selfie / liveness",
    interfaceName: "runSelfieCheck",
    developmentAdapter: "identity.dev",
    productionProvider: "Open — Onfido / Stripe Identity / equivalent",
    dataStoredLocally: "verification_checks (no biometric samples retained in app DB)",
    failureBehaviour: "pending holds profile review; fail does not auto-sanction",
    verificationState: "Sandbox only; never presented as genuine ID",
  },
  {
    feature: "Photo-match",
    interfaceName: "runPhotoMatch",
    developmentAdapter: "identity.dev",
    productionProvider: "Open — same identity vendor",
    dataStoredLocally: "verification_checks, member_photos.verification_status",
    failureBehaviour: "Photo remains unverified; staff can re-run",
    verificationState: "Sandbox only",
  },
  {
    feature: "Image moderation",
    interfaceName: "moderateImage",
    developmentAdapter: "image_moderation.dev",
    productionProvider: "Open — Hive / Sightengine / equivalent",
    dataStoredLocally: "member_photos.moderation_status, jobs, provider_results",
    failureBehaviour: "Job retry; photo stays pending/blurred until clear",
    verificationState: "Sandbox only",
  },
  {
    feature: "Payments / subscriptions",
    interfaceName: "createCheckoutSession",
    developmentAdapter: "payments.dev",
    productionProvider: "Stripe (sandbox then live)",
    dataStoredLocally: "member_profiles.plan_entitlement, provider_results",
    failureBehaviour: "Entitlement stays Free; public checkout flag off in production",
    verificationState: "Sandbox adapter present; PAY-01 lifecycle not complete",
  },
  {
    feature: "Private calls",
    interfaceName: "startPrivateCall",
    developmentAdapter: "calls.dev",
    productionProvider: "Open — Daily / Twilio / LiveKit",
    dataStoredLocally: "provider_results only until MSG-01 rooms exist",
    failureBehaviour: "Call marked unavailable; no phone numbers exposed",
    verificationState: "Interface only until MSG-01",
  },
  {
    feature: "Fraud classification",
    interfaceName: "classifyMessageRisk",
    developmentAdapter: "fraud.dev",
    productionProvider: "Open — rules engine plus vendor",
    dataStoredLocally: "provider_results; later TRU-01 cases",
    failureBehaviour: "unavailable does not silently pass; staff see provider health",
    verificationState: "Interface only until TRU-01",
  },
] as const;
