import { z } from "zod";

/** Founding application submit body. Consents are required — no 201 without them. */
export const SubmitSchema = z.object({
  eligibilityAcknowledged: z.literal(true),
  firstName: z.string().min(1).max(100),
  email: z.string().email(),
  marketingConsent: z.boolean(),
  dateOfBirth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  gender: z.string().min(1),
  seekingGender: z.array(z.string()).min(1),
  ukRegion: z.string().min(1),
  travelRadiusMiles: z.number().int().min(5).max(300),
  religiousDataConsent: z.literal(true),
  religiousDataConsentTimestamp: z.string().min(1),
  religiousDataConsentVersion: z.string(),
  tradition: z.string().min(1),
  churchAttendance: z.string().min(1),
  faithCentrality: z.string().min(1),
  faithDescription: z.string().optional(),
  workStatus: z.string().optional(),
  familySituation: z.string().optional(),
  interests: z.array(z.string()),
  relationshipGoal: z.string().optional(),
  openToRemarriage: z.boolean().nullable(),
  relationshipPace: z.string().optional(),
  ageRangeMin: z.number().int().min(18).max(100),
  ageRangeMax: z.number().int().min(18).max(100),
  preferredDistanceMiles: z.number().int().min(1).max(300),
  meetingPreferences: z.string().optional(),
  essentials: z.array(
    z.object({
      factor: z.string(),
      label: z.string(),
      tier: z.enum(["essential", "preferred", "open"]),
    }),
  ),
  storyPrompt1: z.string().optional(),
  storyPrompt2: z.string().optional(),
  storyPrompt3: z.string().optional(),
  priorities: z.array(z.string()),
  photoConsent: z.boolean(),
  termsAccepted: z.literal(true),
});
