import { useState } from "react";

export function HomepageMobile() {
  const [joined, setJoined] = useState(false);
  return <main className="min-h-[100dvh] bg-[#f7f3ed] text-[#3d2b47] font-['Nunito_Sans']">
    <style>{`@keyframes rise {from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}} .m-rise{animation:rise .7s both} @media(prefers-reduced-motion:reduce){.m-rise{animation:none}}`}</style>
    <header className="flex items-center justify-between px-5 py-5"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full border border-[#9a6f53] text-xs text-[#9a6f53]">M</span><span className="text-[10px] font-bold leading-3 tracking-[.13em] uppercase">Mature Christian<br/>Dating<span className="font-normal text-[#9a6f53]">.co.uk</span></span></div><button onClick={() => setJoined(true)} className="rounded-full border border-[#5e6b5c] px-4 py-2 text-xs font-bold text-[#5e6b5c]">Join free</button></header>
    <section className="relative"><div className="m-rise h-[420px] w-full overflow-hidden"><img src="/__mockup/images/mcd-fl-hero1.jpg" alt="A woman in her early fifties outdoors" className="h-full w-full object-cover object-[center_28%]"/><div className="absolute inset-0 bg-gradient-to-t from-[#3d2b47]/40 to-transparent"/></div><div className="relative -mt-24 mx-5 bg-[#f7f3ed] p-6"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#9a6f53]">A considered way to meet</p><h1 className="mt-4 font-['Lora'] text-[3.25rem] leading-[.96] tracking-[-.07em]">Meet someone who <em className="font-normal text-[#5e6b5c]">shares</em> what matters.</h1><p className="mt-5 text-base leading-7 text-[#697064]">Christian dating for your next chapter. More intention. Less swiping.</p><button onClick={() => setJoined(true)} className="mt-7 w-full rounded-full bg-[#3d2b47] px-5 py-4 text-sm font-bold text-[#f7f3ed]">Become a Founding Member — Free <span className="ml-2">↗</span></button><p className="mt-4 text-center text-[11px] text-[#8b8b7e]">No public member counts. No promises of a match.</p></div></section>
    <section className="bg-[#e8ebe1] px-6 py-16"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#9a6f53]">A different starting point</p><h2 className="mt-4 font-['Lora'] text-4xl leading-tight">Start with <em className="font-normal text-[#5e6b5c]">what matters.</em></h2><p className="mt-5 text-base leading-7 text-[#4e584d]">We ask better questions before we make an introduction. Your faith, your life stage, your intentions, and the everyday things that make a life feel good.</p><div className="mt-8 space-y-0 border-t border-[#c7cdbf]">{["Tell us your story","Share what you value","We look for alignment","Consider an introduction"].map((x,i)=><div key={x} className="flex gap-5 border-b border-[#c7cdbf] py-4 text-sm text-[#5e6b5c]"><b className="font-['Lora'] text-xl text-[#3d2b47]">0{i+1}</b>{x}</div>)}</div></section>
    <section className="px-6 py-16"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#9a6f53]">Fictional examples</p><h2 className="mt-4 font-['Lora'] text-4xl leading-tight">An introduction<br/><em className="font-normal text-[#5e6b5c]">should have a reason.</em></h2><div className="mt-10 border-l-2 border-[#c68a63] pl-5"><p className="font-['Lora'] text-2xl">Sarah, 53</p><p className="text-sm text-[#697064]">Buckinghamshire</p><div className="my-6 h-px w-12 bg-[#c68a63]"/><p className="font-['Lora'] text-2xl">David, 57</p><p className="text-sm text-[#697064]">Oxfordshire</p></div><div className="mt-10 space-y-0">{[["Faith","Church community is important to both"],["Relationship","Both seeking a committed long-term relationship"],["Life stage","Both have adult children"],["Distance","46 miles · Open to travelling up to 60 miles"],["Lifestyle","Travel, countryside walks, live music"]].map(([a,b])=><div key={a} className="flex gap-4 border-b border-[#ddd8ce] py-4 text-sm"><span className="w-20 shrink-0 text-[10px] font-bold uppercase tracking-wide text-[#9a6f53]">{a}</span><span className="text-[#5e6b5c]">{b}</span></div>)}</div></section>
    <section className="bg-[#3d2b47] px-6 py-16 text-[#f7f3ed]"><h2 className="font-['Lora'] text-4xl leading-tight">Make room for <em className="font-normal text-[#d7b18f]">something meaningful.</em></h2><p className="mt-6 text-base leading-7 text-[#d8d3d0]">Join free. Tell us about yourself and who you're hoping to meet.</p><button onClick={() => setJoined(true)} className="mt-7 w-full rounded-full bg-[#c68a63] px-5 py-4 text-sm font-bold text-[#3d2b47]">Become a Founding Member — Free ↗</button><p className="mt-5 text-[11px] leading-5 text-[#bdb3b9]">We do not guarantee a match — we’ll contact you when we identify a promising mutual connection.</p></section>
    <footer className="px-6 py-7 text-[11px] text-[#747b70]">© 2025 Christian Chapter</footer>
    {joined && <div className="fixed inset-0 z-50 grid place-items-center bg-[#3d2b47]/50 p-5" onClick={() => setJoined(false)}><div onClick={e=>e.stopPropagation()} className="w-full bg-[#f7f3ed] p-7"><button onClick={()=>setJoined(false)} className="float-right text-2xl text-[#9a6f53]">×</button><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#9a6f53]">Founding members</p><h2 className="mt-3 font-['Lora'] text-3xl">A good place to begin.</h2><p className="mt-4 text-sm leading-6 text-[#697064]">Leave your email and we’ll let you know when your first questions are ready.</p><input type="email" placeholder="Your email address" className="mt-5 w-full border-b border-[#aaa99d] bg-transparent py-3 text-sm outline-none"/><button onClick={()=>setJoined(false)} className="mt-6 w-full rounded-full bg-[#3d2b47] py-4 text-sm font-bold text-[#f7f3ed]">Continue</button></div></div>}
  </main>;
}