import React, { useState } from "react";

export function HomepageMobile() {
  const [joined, setJoined] = useState(false);
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#0E1621] text-[#F4F0E8] font-['Space_Grotesk']">
      <style>{`@keyframes m-rise { from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none} } .m-rise{animation:m-rise .8s ease-out both}@media(prefers-reduced-motion:reduce){.m-rise{animation:none}}`}</style>
      <section className="relative min-h-[760px] overflow-hidden">
        <img src="/__mockup/images/mcd-sw-hero1.jpg" alt="Thoughtful man in his late fifties outdoors" className="absolute inset-0 h-[580px] w-full object-cover object-[57%] opacity-75 [mask-image:linear-gradient(to_bottom,black_55%,transparent_100%)]" />
        <div className="absolute inset-0 bg-[linear-gradient(to_bottom,rgba(14,22,33,.45),#0E1621_74%)]" />
        <header className="relative z-10 flex items-center justify-between px-6 py-7"><div className="text-[10px] font-semibold uppercase leading-4 tracking-[.22em]">Mature<br/><span className="text-[#C8A46B]">Christian Dating</span></div><a href="#join" className="border border-[#C8A46B]/70 px-4 py-3 text-[9px] uppercase tracking-[.15em] text-[#E7C892]">Join free</a></header>
        <div className="relative z-10 px-6 pt-44"><p className="m-rise mb-7 text-[9px] uppercase tracking-[.3em] text-[#C8A46B]">For Christian single adults · 40–70</p><h1 className="m-rise font-['Playfair_Display'] text-[3.7rem] leading-[.94] tracking-[-.04em]">Meet someone<br/><em className="font-normal text-[#E4C894]">who shares</em><br/>what matters.</h1><div className="m-rise mt-8 flex gap-4"><span className="h-px mt-3 w-14 bg-[#C8A46B]" /><p className="max-w-[235px] text-[14px] leading-6 text-[#c0c6cc]">Christian dating for your next chapter — with more intention, and less noise.</p></div><a href="#join" className="m-rise mt-10 inline-block bg-[#D4B16F] px-5 py-4 text-[10px] font-semibold uppercase tracking-[.15em] text-[#101923]">Become a Founding Member — Free</a></div>
      </section>
      <section className="px-6 pb-24 pt-5"><p className="mb-5 text-[9px] uppercase tracking-[.3em] text-[#C8A46B]">The premise</p><h2 className="font-['Playfair_Display'] text-[2.8rem] leading-[1.05]">Not a marketplace.<br/><em className="font-normal text-[#D5B777]">A considered beginning.</em></h2><p className="mt-8 text-[16px] leading-7 text-[#b9c2cb]">At this stage of life, the question is rarely “Who is available?” It is “Who might understand the shape of my life?”</p></section>
      <section className="border-y border-[#a5b0bb]/15 bg-[#121e2a]"><img src="/__mockup/images/mcd-sw-hero2.jpg" alt="Confident woman in her early fifties" className="h-[360px] w-full object-cover object-center opacity-75" /><div className="px-6 py-14"><p className="mb-5 text-[9px] uppercase tracking-[.28em] text-[#C8A46B]">Fictional example</p><h2 className="font-['Playfair_Display'] text-4xl leading-tight">Introductions,<br/><em className="font-normal text-[#D5B777]">not recommendations.</em></h2><div className="mt-9 space-y-4 border-l border-[#C8A46B]/70 pl-5 text-[13px] leading-6 text-[#c0c7cf]"><p className="text-[#F4F0E8]">Sarah, 53 · Buckinghamshire<br/><span className="text-[#C8A46B]">←→</span> David, 57 · Oxfordshire</p><p><span className="text-[#C8A46B]">Faith</span> Church community is important to both</p><p><span className="text-[#C8A46B]">Relationship</span> Both seeking a committed long-term relationship</p><p><span className="text-[#C8A46B]">Life stage</span> Both have adult children</p><p><span className="text-[#C8A46B]">Distance</span> 46 miles · Both open to travelling up to 60 miles</p><p><span className="text-[#C8A46B]">Lifestyle</span> Travel, countryside walks, live music</p></div><p className="mt-10 font-['Playfair_Display'] text-2xl">“An introduction should have a reason.”</p></div></section>
      <section id="join" className="px-6 py-24 text-center"><p className="mb-5 text-[9px] uppercase tracking-[.3em] text-[#C8A46B]">The founding community</p><h2 className="font-['Playfair_Display'] text-[2.9rem] leading-tight">A thoughtful start<br/><em className="font-normal text-[#D5B777]">begins with you.</em></h2><p className="mt-8 text-[15px] leading-7 text-[#b9c2cb]">Join free. Tell us about yourself and who you're hoping to meet. We'll look for promising mutual connections as our founding community grows.</p><button onClick={() => setJoined(true)} className="mt-9 w-full bg-[#D4B16F] px-4 py-4 text-[10px] font-semibold uppercase tracking-[.13em] text-[#101923]">{joined ? "Thank you — you're on the list" : "Become a Founding Member — Free"}</button><p className="mt-6 text-[10px] leading-5 text-[#7f8b98]">We do not guarantee a match — we'll contact you when we identify a promising mutual connection.</p></section>
      <footer className="border-t border-[#a5b0bb]/15 px-6 py-7 text-[9px] uppercase leading-5 tracking-[.16em] text-[#8f9aa7]">Christian Chapter<br/>Christian dating for your next chapter.</footer>
    </main>
  );
}

export default HomepageMobile;