import React, { useState } from "react";

export function WizardConfirm() {
  const [shared, setShared] = useState(false);
  return <main className="min-h-screen bg-[#0E1621] px-8 py-16 text-[#F4F0E8] font-['Space_Grotesk']">
    <style>{`@keyframes sw-confirm{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}.sw-confirm{animation:sw-confirm .8s ease-out both}`}</style>
    <div className="sw-confirm mx-auto max-w-[1000px]">
      <header className="flex items-start justify-between"><div className="text-[11px] uppercase leading-4 tracking-[.23em]">Mature<br/><span className="text-[#C8A46B]">Christian Dating</span></div><span className="text-[10px] uppercase tracking-[.25em] text-[#7f8c99]">A thoughtful beginning</span></header>
      <section className="mx-auto max-w-[700px] pt-24 text-center"><p className="text-[10px] uppercase tracking-[.32em] text-[#C8A46B]">Welcome to the community</p><div className="mx-auto mt-10 flex h-[76px] w-[250px] items-center justify-center border border-[#C8A46B] text-[11px] font-medium tracking-[.3em] text-[#D4B16F]">FOUNDING MEMBER</div><h1 className="mt-10 font-['Playfair_Display'] text-[58px] leading-[1.05] tracking-[-.025em]">You're a Founding Member.</h1><p className="mx-auto mt-7 max-w-[570px] text-[17px] leading-8 text-[#b9c2cb]">Your profile is now part of the first Mature Christian Dating community. We'll begin looking for promising mutual connections as the community grows.</p></section>
      <section className="mx-auto mt-20 max-w-[760px] border-y border-[#a5b0bb]/15 py-8"><div className="flex items-center gap-5"><div className="relative h-14 w-14 rounded-full border border-[#C8A46B]"><div className="absolute inset-1 rounded-full border border-[#C8A46B]/30" /><span className="absolute inset-0 flex items-center justify-center font-['Playfair_Display'] text-[15px] text-[#D4B16F]">90%</span></div><h2 className="font-['Playfair_Display'] text-[27px]">Your profile</h2></div><div className="mt-7 flex gap-8 text-[13px] text-[#D4B16F]"><span>About you ✓</span><span>Your faith ✓</span><span>Your story ✓</span><span className="text-[#7f8c99]">Photos — add later →</span></div></section>
      <section className="mx-auto mt-20 max-w-[1000px]"><p className="text-[10px] uppercase tracking-[.3em] text-[#C8A46B]">What happens next</p><div className="mt-8 grid grid-cols-3 gap-12">{["Your profile is reviewed by our team.","We look for someone whose faith, life stage, and intentions align with yours.","If we find a promising connection, we'll invite you both to consider an introduction."].map((x,i)=><div key={x} className="border-t border-[#C8A46B]/60 pt-5"><div className="font-['Playfair_Display'] text-3xl text-[#C8A46B]">0{i+1}</div><p className="mt-4 text-[15px] leading-7 text-[#b9c2cb]">{x}</p></div>)}</div></section>
      <section className="mx-auto mt-20 max-w-[760px] border-t border-[#a5b0bb]/15 pt-8"><p className="text-[16px] text-[#F4F0E8]">Know someone who might appreciate a different kind of Christian dating?</p><button type="button" onClick={() => setShared(true)} className="mt-4 min-h-[48px] border-b border-[#C8A46B] pb-1 text-[13px] text-[#D4B16F]">{shared ? "Thank you for sharing" : "Share Mature Christian Dating →"}</button></section>
      <footer className="mx-auto mt-16 flex max-w-[760px] items-center justify-between"><button type="button" className="min-h-[52px] bg-[#D4B16F] px-8 text-[12px] font-semibold uppercase tracking-[.17em] text-[#101923]">View your profile</button><button type="button" className="min-h-[48px] text-[14px] text-[#b9c2cb] hover:text-[#F4F0E8]">Return to homepage</button></footer>
    </div>
  </main>;
}
export default WizardConfirm;